INFO     common.logUtil:test_wms.py:23 -^^--^^--^^--^^--^^--^^-正在执行库区管理的测试，用例id为：3 用例标题为：新增库区_备货区  —^^-—^^-—^^-—^^-—^^-—^^-
INFO     common.logUtil:test_wms.py:30      ***正在发送POST请求---
INFO     common.logUtil:general_func.py:59      ***正在进行结果判断比较---
WARNING  common.logUtil:general_func.py:92      <××××××>用例执行未通过
期望的目标值为：['success', 'True'],
找到的目标值为:['False']
 
用例请求体为：{"name":"测试库区2","typeCode":2,"typeName":"备货区","area":"0"} 
请求url为:https://beta-wms.zhican.com/api/v1/warehouse/warehouseArea/add 
请求头为：{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIyNDciLCJ6Yy11c2VyLWlkIjoyNDcsInpjLXVzZXItbmFtZSI6InBwIiwiZXhwIjoxNjY0OTgyNzE4fQ.Ngo745CgVe5OdBeAOFuBe0BcNBO1pjnVlijQyc2OoPVn3IoA2GBrLvLrteHCShaPbmXyaA2FedA_t1x0Lk0SILmmhqmdvW2blX_xC7c04mwGHZlj3kXiwd-YUNSpLT-lCyrBSEnA_g9wb1iEPBSILtvAiaQ8nhgU_RGiODELtjQIDFHMIGLUZTCvtXmiD0odmKYIUhCcC9wItzjV2asJniQVEof_kGswLyEV8mN96AQrx7Iv7GPkTYUOopgPhM03ELx_rGkt5OrAIXS3vClHzu3eJBjI5-t2xtt4VnwfDzuRNbQqdZMWeAZFTp25VcL8KWAUgYMaZSs7umSSopnxuA', 'client-id': 'erp-client', 'system-type': '1', 'current-warehouse-id': '233'} 
请求方式为：post
服务器返回为{'success': False, 'errCode': '12004', 'errMessage': '库区名称重复！'}
INFO     common.logUtil:general_func.py:99      <√√√√√√>  测试用例id: 3 标题： 新增库区_备货区  通过
INFO     common.logUtil:general_func.py:100 _$__$__$__$__$__$_id: 3 标题: 新增库区_备货区 测试结束_$__$__$_